-- Use this file to define your SQL tables
-- The SQL in this file will be executed when you run `npm run setup-db`
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS achievements;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR,
  password_hash VARCHAR NOT NULL,
  first_name VARCHAR NOT NULL,
  last_name VARCHAR NOT NULL
);

CREATE TABLE achievements (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  title VARCHAR NOT NULL, 
  detail VARCHAR NOT NULL,
  reward INT NOT NULL,
  achievement_points INT NOT NULL
);

INSERT INTO achievements (
  title,
  detail,
  reward,
  achievement_points
)
VALUES
  ('You Shall Be Called Tundra!', 'Acquired A Mount', 1, 2),
  ('Hey! I Speak That!', 'Act As The Party Translator', 1, 1),
  ('Raining That Gold', 'Amass 1,000 Gold Pieces', 1, 3),
  ('Why DM God, Why?', 'Argue With The DM Over A Dice Roll', 1, 1),
  ('I Will Pray Always!', 'Ask A Deity For A Favor', 1, 4),
  ('Stun Grenade!', 'Be Deaf And Blind Simultaneously', 1, 2),
  ('Overruled!', 'Be Ignored By The DM When Citing The Rules', 1, 1),
  ('... Checks Watch', 'Be The First Person To The Game', 1, 1),
  ('My Dog Tripped Me', 'Be The Last Person To The Game', 1, 1),
  ('Fate Smiles On Me Alone', 'Be The Only Person To Roll A Nat 20 At A Session', 1, 3),
  ('Yeah, I Can Act', 'Beat A Performance Check While In Disguise', 1, 2),
  ('VICTORY!', 'Beat The Campaign', 2, 0),
  ('Yes, Bow To Me', 'Become Deified', 2, 0),
  ('Well, That Is A Twist!', 'Betray The Party For Your Own Gain', 2, 0),
  ('Homewrecker', 'Break Up An NPC Marriage Or Relationship', 1, 3),
  ('OH YEAH!', 'Burst Through A Wall', 1, 3),
  ('Sorry Professor, I Must Not Tell Lies!', 'Call Out A Lying NPC', 1, 1),
  ('Oh.. My Bad Friends..', 'Cause A Total Party Kill', 2, 0),
  ('I Am Risen', 'Come Back From 0 HP', 1, 1),
  ('We Are Monsters..', 'Commit Genocide', 2, 0),
  ('Missionary Position', 'Convert An NPCs Religion', 1, 4),
  ('I Read The Cards', 'Correctly Predict Another PCs Permanent Death', 1, 5),
  ('Too Much?', 'Deal 20 Overkill Damage To 1 Enemy', 1, 4),
  ('Let Us All Be Friends', 'Deal No Damage In An Encounter', 1, 5),
  ('Sir Guillotine', 'Decapitate 20 Enemies', 2, 0),
  ('Use Your Words!', 'Defeat An Enemy Using Only Social Skills', 1, 5),
  ('FINISH HIM', 'Deliver 10 Killing Blows', 1, 2),
  ('WHOOPSIE!', 'Destroy An Item Necessary For A Quest', 1, 5),
  ('I Forgot Earth Day', 'Destroy The Planet', 2, 0),
  ('Tell My Wife I Love Her', 'Permanently Die For The First Time', 2, 0),
  ('Tell Her Again', 'Permanently Die For The Second Time', 2, 0),
  ('Third Time Is A Charm!', 'Permanently Die For The Third Time', 2, 0),
  ('Umm... Is It Red?', 'Become Downed From A Puzzle', 1, 3),
  ('Butterfingers', 'Disarm An NPC', 1, 1), 
  ('I Brought My Hard Hat', 'Discover A Trap Before It Discovers You', 1, 2),
  ('Like The Wind', 'Do Not Take Damage While Actively Fighting', 2, 0),
  ('Heart Of Ice', 'Enslave A People', 2, 0),
  ('SIMP Alert!', 'Expect Sexual Favors For Saving An NPC', 1, 1),
  ('That Is All She Wrote', 'Experience A Total Party Kill', 2, 0),
  ('Bloody Brilliant Professor!', 'Experience A Transmutation', 1, 4),
  ('Karma Is A Bitch', 'Experience Revenge From An Old Enemy', 1, 2), 
  ('Red Herring', 'Fall For A Red Herring', 1, 3),
  ('Back Into The Light!', 'Finish A Dungeon', 1, 1),
  ('Are You Not Entertained?', 'Finish An Encounter Within 10 Rounds', 1, 1),
  ('Clever Girl', 'Flank And Kill An Unsuspecting Enemy', 1, 3),
  ('Breaker Of Chains', 'Free 20 Captive People', 2, 0),
  ('Ohhh Sexy!', 'Obtain A Better Set Of Armor', 1, 1),
  ('I Solemnly Swear', 'Obtain A Map', 1, 1),
  ('MY LEG!', 'Get A Permanent Deformity', 2, 0),
  ('Wait, Go Back!', 'Get A Worse Result In A Reroll', 1, 2), 
  ('Tis But A Scratch', 'Get Dismembered', 2, 0),
  ('Not Welcome Back!', 'Get Kicked Out Of A Public Establishment', 1, 2),
  ('My Fault, Friends!', 'Get Your Entire Party Dragged Into Trouble', 1, 1),
  ('What Is Even Sleep?', 'Go Three Encounters Without A Long Rest', 2, 0),
  ('Who Needs Em?', 'Go A Full Session Without Touching Your Dice', 1, 5),
  ('Take It All!', 'Go Broke', 1, 1),
  ('BIG HUG!', 'Grapple Enemies Three Times In One Encounter', 1, 4),
  ('Rasputin', 'Have Three Types Of Impairing Conditions At Once', 1, 5), 
  ('Constructive Bullying', 'Have The Party Gang Up On A Single Enemy', 1, 1),
  ('I Was Born In It', 'Hit An Enemy In Complete Darkness', 1, 3),
  ('I Do Not Have Time For That', 'Ignore A Crucial Plot Point', 1, 2),
  ('SPARTA!', 'Kick Someone Off A Ledge To Their Death', 1, 2),
  ('Not Even My Final Form', 'Kill Three Enemies While At Half Health In One Encounter', 1, 3),
  ('Deus Ex', 'Kill A Diety', 2, 0),
  ('Full Scales', 'Kill A Dragon', 2, 0),
  ('Not My President', 'Kill A Loved Political Figure', 2, 0),
  ('SMITE', 'Kill An Enemy Using A Holy Weapon', 1, 5), 
  ('SHOWOFF', 'Kill All Enemies In An Encounter Yourself', 1, 5),
  ('OMG, Shut Up', 'Kill An Annoying NPC', 1, 2),
  ('Brainpower', 'Kill An Enemy Using Only Skill Checks', 1, 4),
  ('Sick Em!', 'Kill An Enemy With An Animal', 1, 3),
  ('Whose Life Is It Anyways?', 'Kill An Enemy With An Improvised Weapon', 1, 3),
  ('PERFECT!', 'Kill An Enemy With Zero Overkill Damage', 1, 5),
  ('From The Shadows', 'Kill An Enemy Without Being Seen Or Heard', 1, 3),
  ('Double Tap!', 'Kill An Undead Enemy With A Headshot', 1, 3),
  ('Long Live The King', 'Kill And Replace A Sovereign Leader', 2, 0),
  ('Ugh.. It Was Him!', 'Kill Someone In A Public Place', 1, 1), 
  ('I Was Told To', 'Kill Someone In The Name Of A God', 1, 1),
  ('Situational Awareness', 'Kill Someone Using The Environment', 1, 2),
  ('Glutton For Punishment', 'Knowingly Activate A Trap', 1, 1),
  ('Vote For Me!', 'Legitimately Achieve A High Political Status', 2, 0),
  ('It Is Just Business..', 'Let A Fellow PC Permanently Die For Your Personal Gain', 2, 0), 
  ('Molotov', 'Lob A Flaming Projectile At An Enemy', 1, 1), 
  ('That Is All She Wrote...', 'Lose The Campaign', 2, 0),
  ('The Power Of One', 'Make A Success / Fail Difference With A +1 Buff', 2, 0), 
  ('I Am BAAAAACK!', 'Meet With A Reccurring Villain', 1, 1),
  ('2+2=5?', 'Miscount Gold While Splitting The Loot', 1, 1),
  ('Psychic', 'Mix Player And Character Knowledge', 1, 1),
  ('CRITorium', 'Open A Shop In A Settlement', 1, 3),
  ('FREEEDOM!', 'Overthrow A Government', 2, 0),
  ('Shake And Bake', 'Perform A Combo With A Fellow PC', 1, 2),
  ('Is This Chicken?', 'Practice Cannabalism', 1, 1),
  ('Stop Hitting Yourself', 'Reach Zero HP From A Fumbled Attack Roll', 2, 0),
  ('Hello Darkness... Again', 'Reach Zero HP Twice In One Encounter', 1, 2),
  ('A Mission From God', 'Receive Divine Direction', 2, 0),
  ('Peace To All', 'Reconcile Differences Between Mortal Enemies', 1, 5), 
  ('Life Alert', 'Remain Prone For Three Consecutive Turns', 1, 2),
  ('Priestly', 'Resolve A Religious Conflict Nonviolently', 1, 4),
  ('French Tactics', 'Retreat From Five Battles', 1, 4),
  ('My Precious!', 'Retrieve A MacGuffin', 1, 3),
  ('Haha, You Thought!', 'Revive An NPC Just To Kill Them Yourself', 1, 1),
  ('Take A Bow!', 'Roleplay A Character Acceptionally Well', 1, 3),
  ('Twisted Ankle', 'Roll A NAT One On An Acrobatics Check', 1, 2),
  ('Bite The Hand That Feeds', 'Roll A NAT One On An Animal Handling Check', 1, 2),
  ('What Magic?', 'Roll A NAT One On An Arcana Check', 1, 2),
  ('Doth Thou Even Hoist?', 'Roll A NAT One On An Athletics Check', 1, 2),
  ('I Will See Myself Out', 'Roll A NAT One On A Deception Check', 1, 2),
  ('No History Buff Here', 'Roll A NAT One On A History Check', 1, 2),
  ('I Just Can Not Tell..', 'Roll A NAT One On An Insight Check', 1, 2),
  ('I Scare Myself', 'Roll A NAT One On An Intimidation Check', 1, 2),
  ('Detective Obvious', 'Roll A NAT One On An Investigation Check', 1, 2),
  ('Dr. Oz', 'Roll A NAT One On A Medicine Check', 1, 2),
  ('Nature Sucks', 'Roll A NAT One On A Nature Check', 1, 2),
  ('Perceive This..', 'Roll A NAT One On A Perception Check', 1, 2),
  ('Bring The Little Blue Pills!', 'Roll A NAT One On A Performance Check', 1, 2),
  ('Because I Said So', 'Roll A NAT One On A Persuasion Check', 1, 2),
  ('On Faith Alone', 'Roll A NAT One On A Religion Check', 1, 2),
  ('I Will Just Put That Back..', 'Roll A NAT One On A Sleight Of Hand Check', 1, 2),
  ('You Can Not See Me!', 'Roll A NAT One On A Stealth Check', 1, 2),
  ('I Survive Nothing', 'Roll A NAT One On A Survival Check', 1, 2),
  ('Gold Medal Gymnast', 'Roll A Nat 20 On An Acrobatics Check', 1, 2),
  ('Call Me Noah', 'Roll A Nat 20 On An Animal Handling Check', 1, 2),
  ('Magic Is My Middle Name', 'Roll A Nat 20 On An Arcana Check', 1, 2),
  ('I Can Do All The Push Ups', 'Roll A Nat 20 On An Athletics Check', 1, 2),
  ('Trust Me', 'Roll A Nat 20 On A Deception Check', 1, 2),
  ('Pretty Sure I Was There', 'Roll A Nat 20 On A History Check', 1, 2),
  ('Try Again Loser, You Can Not Fool Me', 'Roll A Nat 20 On An Insight Check', 1, 2),
  ('Do Not Even Look At Me', 'Roll A Nat 20 On An Intimidation Check', 1, 2),
  ('Sherlock Holmes', 'Roll A Nat 20 On An Investigation Check', 1, 2),
  ('Call Me Dr. Morphine', 'Roll A Nat 20 On A Medicine Check', 1, 2),
  ('Am I Part Druid?', 'Roll A Nat 20 On A Nature Check', 1, 2),
  ('I.. Percieve.. Everything', 'Roll A Nat 20 On A Perception Check', 1, 2),
  ('No Sweat, I Can Do It Again', 'Roll A Nat 20 On A Performance Check', 1, 2),
  ('Believe In Me', 'Roll A Nat 20 On A Persuasion Check', 1, 2),
  ('I Am A Prophet', 'Roll A Nat 20 On A Religion Check', 1, 2),
  ('I Will Take That As Well, Thank You', 'Roll A Nat 20 On A Sleight Of Hand Check', 1, 2),
  ('I Am The Darkness', 'Roll A Nat 20 On A Stealth Check', 1, 2),
  ('Call Me Bear Grylls', 'Roll A Nat 20 On A Survival Check', 1, 2),
  ('It Is LEVI-OH-SAH!', 'Roll A One On A Spell Cast', 1, 1),
  ('I Will Just Be Back Here Then..', 'Roll A NAT One On An Initiative Check', 1, 1),
  ('EVERYONE BEHIND ME!', 'Roll A NAT 20 On An Initiative Check', 1, 1),
  ('All The Luck!', 'Roll Two Oness In A Row', 1, 4),
  ('I AM DONE', 'Roll Two Ones On An Advantaged Roll', 1, 4),
  ('Seriously, Bow To Me', 'Roll Two 20s in A Row', 1, 4),
  ('What Is Disadvantage?', 'Roll Two 20s On A Disadvantaged Roll', 1, 4),
  ('I Volunteer As Tribute!', 'Sacrifice Yourself, Resulting In Permanent Death', 2, 0),
  ('Friendship Is Key', 'Save A PC In Need', 1, 2),
  ('Batting Average Garbage', 'Score 3 Melee Misses In One Encounter', 1, 3),
  ('Storm Trooper Shots', 'Score 3 Ranges Misses In One Encounter', 1, 3),
  ('Sexual Tyrannosaurus', 'Seduce An NPC', 1, 3),
  ('Chaos Is A Ladder', 'Shift Your Alignment To Chaotic', 1, 5),
  ('No Turning Back...', 'Shift Your Alignment To Evil', 1, 5),
  ('Suck It, Boromir', 'Simply Walk Into A Well Guarded Place', 1, 1),
  ('That Still Only Counts As One', 'Solo A Large Monster', 2, 0),
  ('I Scratch My Head', 'Spend More Than Thirty Minutes On A Puzzle', 1, 1),
  ('I Will Go Left, You Go Right!', 'Split The Party', 1, 1),
  ('Live, Damn You!', 'Stabilize A Dying Character', 1, 1),
  ('99 Red Balloons', 'Start A War Between Two Or More Countries', 2, 0),
  ('Like Glue', 'Steal More Than 100 Gold', 1, 2),
  ('Never Tell Me The Odds', 'Succeed Only Because You Rolled A NAT 20', 1, 2),
  ('For King And Country', 'Successfully Defend A Royal Life', 2, 0),
  ('Does He Look Like A Bitch?', 'Successfully Interrogate An NPC', 1, 1),
  ('Stop, Drop, And Roll!', 'Survive Three Rounds Of Ongoing Fire Damage', 1, 2), 
  ('How Many Snakes On This Plane?!', 'Survive 50 points of Poison Damage', 1, 5),
  ('I Am Okay', 'Survive A Crit', 1, 1),
  ('Bring Me My Larger Ship!', 'Survive A Fight With A Sea Monster', 2, 0),
  ('Nice Warm Sand', 'Experience A Ship Wreck', 1, 3),
  ('25% And A Dream', 'Survive An Encounter With A Quarter Health', 1, 2), 
  ('It Is In The Pipes', 'Survive Being Petrified', 1, 5),
  ('You Talk Too Much', 'Take Advantage Of A Talkative Villain', 1, 2),
  ('Donate It!', 'Take An Artifact From A Dungeon', 1, 1),
  ('Move Along, Nothing To See Here', 'Take And/Or Give Ten Bribes', 1, 4),
  ('Backwoods Shannanigans', 'Take Drugs In The Campaign', 1, 1),
  ('Get On With It!', 'Talk Out Of Character For Longer Than One Minute', 1, 1),
  ('Insert Your Mom Joke Here', 'Taunt An Enemy To Get Their Attention', 1, 1),
  ('Dobby Is Free!', 'Team Up With An NPC Sidekick', 1, 3),
  ('It Is SUUUUPER Effective!', 'Trigger An Enemies Vulnerability', 1, 1),
  ('It Makes Sense In My Head...', 'Use Poor Logic In A Persuasion Check', 1, 1),
  ('Shut Up Donnie!', 'Verbally Abuse A Fellow PC', 1, 1), 
  ('A Farewell To Arms', 'Willingly Remove A Limb', 2, 0),
  ('Bottoms Up!', 'Win A Drinking Contest', 1, 1),
  ('Objection!', 'Win A Legal Case', 1, 5);