-- Use this file to define your SQL tables
-- The SQL in this file will be executed when you run `npm run setup-db`
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS achievements;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR,
  password_hash VARCHAR NOT NULL,
  first_name VARCHAR NOT NULL,
  last_name VARCHAR NOT NULL
);

CREATE TABLE achievements (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  title VARCHAR NOT NULL, 
  detail VARCHAR NOT NULL, 
  attained_detail VARCHAR,
  dm_reasoning VARCHAR
);

INSERT INTO achievements (
  title,
  detail,
  attained_detail,
  dm_reasoning
)
VALUES
  ('You Shall Be Called Tundra!', 'Acquired A Mount', '',''),
  ('Hey! I Speak That!', 'Act As The Party Translator', '', ''),
  ('Raining That Gold', 'Amass 1,000 Gold Pieces', '', ''),
  ('Why DM God, Why?', 'Argue With The DM Over A Dice Roll', '', ''),
  ('I Will Pray Always!', 'Ask A Diety For A Favor', '', ''),
  ('Stun Grenade!', 'Be Deaf And Blind Simultaneously', '', ''),
  ('Overruled!', 'Be Ignored By The DM When Citing The Rules', '', ''),
  ('... Checks Watch', 'Be The First Person To The Game', '', ''),
  ('My Dog Tripped Me', 'Be The Last Person To The Game', '', ''),
  ('Fate Smiles On Me Alone', 'Be The Only Person To Roll A Nat 20 At A Session', '', ''),
  ('Yeah, I Can Act', 'Beat A Performance Check While In Disguise', '', ''),
  ('VICTORY!', 'Beat The Campaign', '', ''),
  ('Yes, Bow To Me', 'Become Deified', '', ''),
  ('Well, That Is A Twist!', 'Betray The Party For Your Own Gain', '', ''),
  ('Homewrecker', 'Break Up An NPC Marriage Or Relationship', '', ''),
  ('OH YEAH!', 'Burst Through A Wall', '', ''),
  ('Sorry Professor, I Must Not Tell Lies!', 'Call Out A Lying NPC', '', ''),
  ('Oh.. My Bad Friends..', 'Cause A Total Party Kill', '', ''),
  ('I Am Risen', 'Come Back From 0 HP', '', ''),
  ('We Are Monsters..', 'Commit Genocide', '', ''),
  ('Missionary Position', 'Convert An NPCs Religion', '', ''),
  ('I Read The Cards', 'Correctly Predict Another PCs Death', '', ''),
  ('Too Much?', 'Deal 20 Overkill Damage To 1 Enemy', '', ''),
  ('Let Us All Be Friends', 'Deal No Damage In An Encounter', '', ''),
  ('Sir Guillotine', 'Decapitate 20 Enemies', '', ''),
  ('Use Your Words!', 'Defeat An Enemy Using Only Social Skills', '', ''),
  ('FINISH HIM', 'Deliver 10 Killing Blows', '',''),
  ('WHOOPSIE!', 'Destroy An Item Necessary For A Quest', '', ''),
  ('I Forgot Earth Day', 'Destroy The Planet', '', ''),
  ('Tell My Wife I Love Her', 'Die For The First Time', '', ''),
  ('Tell Her Again', 'Die For The Second Time', '', ''),
  ('Third Time Is A Charm!', 'Die For The Third Time', '', ''),
  ('Umm... Is It Red?', 'Die From A Puzzle', '', ''),
  ('Butterfingers', 'Disarm An NPC', '', ''), 
  ('I Brought My Hard Hat', 'Discover A Trap Before It Discovers You', '', ''),
  ('Like The Wind', 'Do Not Take Damage In An Encounter', '', ''),
  ('Heart Of Ice', 'Enslave A People', '', ''),
  ('SIMP Alert!', 'Expect Sexual Favors For Saving An NPC', '', ''),
  ('That Is All She Wrote', 'Experience A Total Party Kill', '', ''),
  ('Bloody Brilliant Professor!', 'Experience A Transmutation', '', ''),
  ('Karma Is A Bitch', 'Experience Revenge From An Old Enemy', '', ''), 
  ('Red Herring', 'Fall For A Red Herring', '', ''),
  ('Back Into The Light!', 'Finish A Dungeon', '', ''),
  ('Are You Not Entertained?', 'Finish An Encounter Within 10 Rounds', '', ''),
  ('Clever Girl', 'Flank And Kill An Unsuspecting Enemy', '', ''),
  ('Breaker Of Chains', 'Free 20 Captive People', '', ''),
  ('Ohhh Sexy!', 'Obtain A Better Set Of Armor', '', ''),
  ('I Solemnly Swear', 'Obtain A Map', '', ''),
  ('MY LEG!', 'Get A Permanent Deformity', '', ''),
  ('Wait, Go Back!', 'Get A Worse Result In A Reroll', '', ''), 
  ('Tis But A Scratch', 'Get Dismembered', '', ''),
  ('Not Welcome Back!', 'Get Kicked Out Of A Public Establishment', '', ''),
  ('My Fault, Friends!', 'Get Your Entire Party Dragged Into Trouble', '', ''),
  ('What Is Even Sleep?', 'Go 3 Days Without A Long Rest', '', ''),
  ('Who Needs Em?', 'Go A Full Session Without Touching Your Dice', '', ''),
  ('Take It All!', 'Go Broke', '', ''),
  ('BIG HUG!', 'Grapple Enemies 3 Times In One Encounter', '', ''),
  ('Rasputin', 'Have 3 Types Of Impairing Conditions At Once', '', ''), 
  ('Constructive Bullying', 'Have The Party Gang Up On A Single Enemy', '', ''),
  ('I Was Born In It', 'Hit An Enemy In Complete Darkness', '', ''),
  ('I Do Not Have Time For That', 'Ignore A Crucial Plot Point', '', ''),
  ('SPARTA!', 'Kick Someone Off A Ledge To Their Death', '', ''),
  ('Not Even My Final Form', 'Kill 3 Enemies While At Half Health In One Encounter', '', ''),
  ('Deus Ex', 'Kill A Diety', '', ''),
  ('Full Scales', 'Kill A Dragon', '', ''),
  ('Not My President', 'Kill A Loved Political Figure', '', ''),
  ('SMITE', 'Kill An Enemy Using A Holy Weapon', '', ''), 
  ('SHOWOFF', 'Kill All Enemies In An Encounter Yourself', '', ''),
  ('OMG, Shut Up', 'Kill An Annoying NPC', '', ''),
  ('Brainpower', 'Kill An Enemy Using Only Skill Checks', '', ''),
  ('Sick Em!', 'Kill An Enemy With An Animal', '', ''),
  ('Whose Life Is It Anyways?', 'Kill An Enemy With An Improv Weapon', '', ''),
  ('PERFECT!', 'Kill An Enemy With 0 Overkill Damage', '', ''),
  ('From The Shadows', 'Kill An Enemy Without Being Seen Or Heard', '', ''),
  ('Double Tap!', 'Kill An Undead Enemy With A Headshot', '', ''),
  ('Long Live The King', 'Kill And Replace A Sovereign Leader', '', ''),
  ('Ugh.. It Was Him!', 'Kill Someone In A Public Place', '', ''), 
  ('I Was Told To', 'Kill Someone In The Name Of A God', '', ''),
  ('Situational Awareness', 'Kill Someone Using The Environment', '', ''),
  ('Glutton For Punishment', 'Knowingly Activate A Trap', '', ''),
  ('Vote For Me!', 'Legitimately Achieve A High Political Status', '', ''),
  ('It Is Just Business..', 'Let A Fellow PC Die For Your Personal Gain', '', ''), 
  ('Molotov', 'Lob A Flaming Projectile At An Enemy', '', ''), 
  ('That Is All She Wrote...', 'Lose The Campaign', '', ''),
  ('The Power Of One', 'Make A Success / Fail Difference With A +1 Buff', '', ''), 
  ('I Am BAAAAACK!', 'Meet With A Reccurring Villain', '', ''),
  ('2+2=5?', 'Miscount Gold While Splitting The Loot', '', ''),
  ('Psychic', 'Mix Player And Character Knowledge', '', ''),
  ('CRITorium', 'Open A Shop In A Settlement', '', ''),
  ('FREEEDOM!', 'Overthrow A Government', '', ''),
  ('Shake And Bake', 'Perform A Combo With A Fellow PC', '', ''),
  ('Is This Chicken?', 'Practice Cannabalism', '', ''),
  ('Stop Hitting Yourself', 'Reach 0 HP From A Fumbled Attack Roll', '', ''),
  ('Hello Darkness... Again', 'Reach 0 HP Twice In One Encounter', '', ''),
  ('A Mission From God', 'Receive Divine Direction', '', ''),
  ('Peace To All', 'Reconcile Differences Between Mortal Enemies', '', ''), 
  ('Life Alert', 'Remain Prone For 3 Consecutive Turns', '', ''),
  ('Priestly', 'Resolve A Religious Conflict Nonviolently', '', ''),
  ('French Tactics', 'Retreat From 5 Battles', '', ''),
  ('My Precious!', 'Retrieve A MacGuffin', '', ''),
  ('Haha, You Thought!', 'Revive An NPC Just To Kill Them Yourself', '', ''),
  ('Take A Bow!', 'Roleplay A Character Acceptionally Well', '', ''),
  ('Twisted Ankle', 'Roll A 1 On An Acrobatics Check', '', ''),
  ('Bite The Hand That Feeds', 'Roll A 1 On An Animal Handling Check', '', ''),
  ('What Magic?', 'Roll A 1 On An Arcana Check', '', ''),
  ('Doth Thou Even Hoist?', 'Roll A 1 On An Athletics Check', '', ''),
  ('I Will See Myself Out', 'Roll A 1 On A Deception Check', '', ''),
  ('No History Buff Here', 'Roll A 1 On A History Check', '', ''),
  ('I Just Can Not Tell..', 'Roll A 1 On An Insight Check', '', ''),
  ('I Scare Myself', 'Roll A 1 On An Intimidation Check', '', ''),
  ('Detective Obvious', 'Roll A 1 On An Investigation Check', '', ''),
  ('Dr. Oz', 'Roll A 1 On A Medicine Check', '', ''),
  ('Nature Sucks', 'Roll A 1 On A Nature Check', '', ''),
  ('Perceive This..', 'Roll A 1 On A Perception Check', '', ''),
  ('Bring The Little Blue Pills!', 'Roll A 1 On A Performance Check', '', ''),
  ('Because I Said So', 'Roll A 1 On A Persuasion Check', '', ''),
  ('On Faith Alone', 'Roll A 1 On A Religion Check', '', ''),
  ('I Will Just Put That Back..', 'Roll A 1 On A Sleight Of Hand Check', '', ''),
  ('You Can Not See Me!', 'Roll A 1 On A Stealth Check', '', ''),
  ('I Survive Nothing', 'Roll A 1 On A Survival Check', '', ''),
  ('Gold Medal Gymnast', 'Roll A 20 On An Acrobatics Check', '', ''),
  ('Call Me Noah', 'Roll A 20 On An Animal Handling Check', '', ''),
  ('Magic Is My Middle Name', 'Roll A 20 On An Arcana Check', '', ''),
  ('I Can Do All The Push Ups', 'Roll A 20 On An Athletics Check', '', ''),
  ('Trust Me', 'Roll A 20 On A Deception Check', '', ''),
  ('Pretty Sure I Was There', 'Roll A 20 On A History Check', '', ''),
  ('Try Again Loser, You Can Not Fool Me', 'Roll A 20 On An Insight Check', '', ''),
  ('Do Not Even Look At Me', 'Roll A 20 On An Intimidation Check', '', ''),
  ('Sherlock Holmes', 'Roll A 20 On An Investigation Check', '', ''),
  ('Call Me Dr. Morphine', 'Roll A 20 On A Medicine Check', '', ''),
  ('Am I Part Druid?', 'Roll A 20 On A Nature Check', '', ''),
  ('I.. Percieve.. Everything', 'Roll A 20 On A Perception Check', '', ''),
  ('No Sweat, I Can Do It Again', 'Roll A 20 On A Performance Check', '', ''),
  ('Believe In Me', 'Roll A 20 On A Persuasion Check', '', ''),
  ('I Am A Prophet', 'Roll A 20 On A Religion Check', '', ''),
  ('I Will Take That As Well, Thank You', 'Roll A 20 On A Sleight Of Hand Check', '', ''),
  ('I Am The Darkness', 'Roll A 20 On A Stealth Check', '', ''),
  ('Call Me Bear Grylls', 'Roll A 20 On A Survival Check', '', ''),
  ('It Is LEVI-OH-SAH!', 'Roll A 1 On A Spell Cast', '', ''),
  ('I Will Just Be Back Here Then..', 'Roll A 1 On An Initiative Check', '', ''), 
  ('All The Luck!', 'Roll Two 1s In A Row', '', ''),
  ('I AM DONE', 'Roll Two 1s On An Advantaged Roll', '', ''),
  ('Seriously, Bow To Me', 'Roll Two 20s in A Row', '', ''),
  ('What Is Disadvantage?', 'Roll Two 20s On A Disadvantaged Roll', '', ''),
  ('I Volunteer As Tribute!', 'Sacrifice Yourself', '', ''),
  ('Friendship Is Key', 'Save A PC In Need', '', ''),
  ('Batting Average Garbage', 'Score 3 Melee Misses In One Encounter', '', ''),
  ('Storm Trooper Shots', 'Score 3 Ranges Misses In One Encounter', '', ''),
  ('Sexual Tyrannosaurus', 'Seduce An NPC', '', ''),
  ('Chaos Is A Ladder', 'Shift Your Alignment To Chaotic', '', ''),
  ('No Turning Back...', 'Shift Your Alignment To Evil', '', ''),
  ('Suck It, Boromir', 'Simply Walk Into A Well Guarded Place', '', ''),
  ('That Still Only Counts As One', 'Solo A Large Monster', '', ''),
  ('I Scratch My Head', 'Spend More Than Thirty Minutes On A Puzzle', '', ''),
  ('I Will Go Left, You Go Right!', 'Split The Party', '', ''),
  ('Live, Damn You!', 'Stabilize A Dying Character', '', ''),
  ('99 Red Balloons', 'Start A War Between Two Or More Countries', '', ''),
  ('Like Glue', 'Steal More Than 100 Gold', '', ''),
  ('Never Tell Me The Odds', 'Succeed Only Because You Rolled A 20', '', ''),
  ('For King And Country', 'Successfully Defend A Royal Life', '', ''),
  ('Does He Look Like A Bitch?', 'Successfully Interrogate An NPC', '', ''),
  ('Stop, Drop, And Roll!', 'Survive 3 Rounds Of Ongoing Fire Damage', '', ''), 
  ('How Many Snakes On This Plane?!', 'Survive 50 points of Poison Damage', '', ''),
  ('I Am Okay', 'Survive A Crit', '', ''),
  ('Bring Me My Larger Ship!', 'Survive A Fight With A Sea Monster', '', ''),
  ('Nice Warm Sand', 'Survive A Ship Wreck', '', ''),
  ('25% And A Dream', 'Survive An Encounter With 1/4th Health', '', ''), 
  ('It Is In The Pipes', 'Survive Being Petrified', '', ''),
  ('You Talk Too Much', 'Take Advantage Of A Talkative Villain', '', ''),
  ('Donate It!', 'Take An Artifact From A Dungeon', '', ''),
  ('Move Along, Nothing To See Here', 'Take And/Or Give 10 Bribes', '', ''),
  ('Backwoods Shannanigans', 'Take Drugs In The Game', '', ''),
  ('Get On With It!', 'Talk Out Of Character For Longer Than One Minute', '', ''),
  ('Insert Your Mom Joke Here', 'Taunt An Enemy To Get Their Attention', '', ''),
  ('Dobby Is Free!', 'Team Up With An NPC Sidekick', '', ''),
  ('It Is SUUUUPER Effective!', 'Trigger An Enemies Vulnerability', '', ''),
  ('It Makes Sense In My Head...', 'Use Poor Logic In A Persuasion Check', '', ''),
  ('Shut Up Donnie!', 'Verbally Abuse A Fellow PC', '', ''), 
  ('A Farewell To Arms', 'Willingly Remove A Limb', '', ''),
  ('Bottoms Up!', 'Win A Drinking Contest', '', ''),
  ('Objection!', 'Win A Legal Case', '', '');
  
